#!/usr/bin/env python3
"""Build the TEST_PLAN case 20 project: 50 nodes, 75 links, 50 probes.

Writes straight into the SQLite store the app already uses, because the point
is to measure the running app under that load, not to test the import path.

Half the probes target 127.0.0.1 so they go healthy (and therefore animate);
the rest target the RFC 5737 documentation range so they go down. That gives a
mixed canvas — roughly 25-30 animated edges — which is what the case asks for.

  python3 e2e/make_case20.py
"""
import json
import sqlite3
import sys
import time
import uuid
from pathlib import Path

DB = Path.home() / ".local/share/LiveTopo/livetopo.db"
NODES, EDGES = 50, 75
DEVICE_TYPES = [
    "router", "firewall", "core-switch", "access-switch", "distribution-switch",
    "server", "wireless-controller", "access-point", "storage", "virtual-machine",
]

def main() -> int:
    if not DB.exists():
        print(f"no database at {DB} — run the app once first", file=sys.stderr)
        return 1

    pid = str(uuid.uuid4())
    nodes, edges, probes = [], [], []
    ids = [str(uuid.uuid4()) for _ in range(NODES)]

    # 10 columns x 5 rows, generous spacing so edges are long and mostly visible.
    for i, nid in enumerate(ids):
        col, row = i % 10, i // 10
        nodes.append({
            "id": nid,
            "type": "device",
            "position": {"x": col * 260, "y": row * 190},
            "width": 176, "height": 96,
            "measured": {"width": 176, "height": 96},
            "data": {
                "label": f"DEV-{i:02d}",
                "device_type": DEVICE_TYPES[i % len(DEVICE_TYPES)],
                "addresses": [], "tags": [],
                "locked": False, "maintenance": False, "show_details": True,
            },
        })
        # Alternate healthy / down so the canvas has both.
        healthy = i % 2 == 0
        probes.append({
            "id": str(uuid.uuid4()),
            "project_id": pid,
            "object_kind": "node",
            "object_id": nid,
            "name": "mgmt",
            "kind": "icmp",
            "target": "127.0.0.1" if healthy else f"192.0.2.{(i % 200) + 1}",
            "tcp_port": None,
            "interval_seconds": 5,
            "timeout_ms": 1000,
            "failure_threshold": 3,
            "recovery_threshold": 1,
            "warning_latency_ms": 100,
            "enabled": True,
            "is_primary": True,
            "maintenance": False,
        })

    # 49 spine edges so the graph is connected, then 26 extra cross links.
    def edge(a: str, b: str, n: int) -> dict:
        return {
            "id": str(uuid.uuid4()),
            "type": "live",
            "source": a, "target": b,
            "source_handle": "r", "target_handle": "l",
            "data": {
                "label": f"link-{n:02d}",
                "source_port_label": f"Gi1/0/{n % 48 + 1}",
                "target_port_label": f"Gi1/0/{(n * 3) % 48 + 1}",
                "path_type": "smoothstep",
                "direction": "both",
                "color": "#5b6b7c",
                "width": 2,
                "enabled": True,
                "maintenance": False,
                # follow-source means the edge takes its colour (and animation)
                # from the source node's probe.
                "health_rule": {"type": "follow-source"},
            },
        }

    n = 0
    for i in range(NODES - 1):
        edges.append(edge(ids[i], ids[i + 1], n)); n += 1
    i = 0
    while len(edges) < EDGES:
        a, b = ids[i % NODES], ids[(i * 7 + 11) % NODES]
        if a != b:
            edges.append(edge(a, b, n)); n += 1
        i += 1

    doc = {
        "canvas": {"grid": True, "snap": True, "zoom": 1, "x": 0, "y": 0},
        "nodes": nodes, "edges": edges, "probes": probes,
    }
    now = int(time.time() * 1000)
    con = sqlite3.connect(DB)
    cols = [r[1] for r in con.execute("PRAGMA table_info(projects)")]
    row = {
        "id": pid, "name": "CASE-20 — 50 nodes / 75 links",
        "customer": "Perf", "site": "Bench", "ticket": "CASE-20",
        "engineer": "harness", "description": "Generated by e2e/make_case20.py",
        "created_at": now, "updated_at": now, "archived": 0,
        "document_version": 1, "document": json.dumps(doc),
    }
    use = [c for c in cols if c in row]
    con.execute(
        f"INSERT INTO projects ({','.join(use)}) VALUES ({','.join('?' * len(use))})",
        [row[c] for c in use],
    )
    con.commit()
    print(f"created project {pid}")
    print(f"  nodes  {len(nodes)}")
    print(f"  edges  {len(edges)}")
    print(f"  probes {len(probes)}  ({sum(1 for p in probes if p['target'] == '127.0.0.1')} healthy targets)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
